Adding error extension info to entity fetch errors
graph-quilt/graphql-orchestrator-java pull request #142
Opened 2023-01-19 19:23 UTC by kmoore-intuit

# What Changed
Adding error extension info to errors

# Why
Allow partial data with reasons why instead of exception

Todo:

- [ ] Add tests
- [ ] Add docs

2023-01-20 17:40 UTC, CNAChino commented on src/main/java/com/intuit/graphql/orchestrator/batch/EntityFetcherBatchResultTransformer.java
> -        if(dataFetcherResult.hasErrors()) {
nice, the new flow is better

2023-01-20 17:42 UTC, CNAChino commented on src/main/java/com/intuit/graphql/orchestrator/batch/EntityFetcherBatchResultTransformer.java
> +            List<GraphQLError> graphQLErrors = (List<GraphQLError>) entityInfo.getOrDefault("errors", new ArrayList<>());
👍

2023-01-20 17:51 UTC, CNAChino commented on src/main/java/com/intuit/graphql/orchestrator/batch/EntityFetcherBatchResultTransformer.java
> +            log.warn("Provider {} is not using DGS or invalid version", providerNamespace);
I suggest log: "Provider {} is not Federation subgraph specification compliant.  _entities field missing or empty in the response."

2023-01-20 18:05 UTC, CNAChino commented on src/main/java/com/intuit/graphql/orchestrator/batch/EntityFetcherBatchResultTransformer.java
> +                //Decided to ignore if errors have no path to match field resolver. This should not happen though.
i'm not 100% if should if ignore, we can discuss

2023-01-20 18:09 UTC, CNAChino commented on src/main/java/com/intuit/graphql/orchestrator/batch/EntityFetcherBatchResultTransformer.java
> +                    Integer pathIndex = (Integer) error.getPath().get(1);
i suggest use constant instead of magic number 1.

2023-01-20 18:16 UTC, CNAChino commented on src/main/java/com/intuit/graphql/orchestrator/batch/EntityFetcherBatchResultTransformer.java
> +                       List<GraphQLError> errors = (List<GraphQLError>) entityInfo.get("errors");
I'm not sure if the entity field contains errors?  I think it should be in dataFetcherResult.getErrors.

2023-01-24 19:21 UTC, ashpak-shaikh approved these changes

2023-01-25 18:14 UTC, ashpak-shaikh requested changes
LGTM, add e2e integration test with 2 providers.

2023-02-01 18:58 UTC, ashpak-shaikh approved these changes

2023-02-01 18:58 UTC, merged